// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ThreadUpdate Сообщение для обновления ветки обсуждения на форуме.
// Пустые параметры остаются без изменений.
//
//
// swagger:model ThreadUpdate
type ThreadUpdate struct {

	// Описание ветки обсуждения.
	// Example: An urgent need to reveal the hiding place of Davy Jones. Who is willing to help in this matter?
	Message string `json:"message,omitempty"`

	// Заголовок ветки обсуждения.
	// Example: Davy Jones cache
	Title string `json:"title,omitempty"`
}

// Validate validates this thread update
func (m *ThreadUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this thread update based on context it is used
func (m *ThreadUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ThreadUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ThreadUpdate) UnmarshalBinary(b []byte) error {
	var res ThreadUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
